[project]
name = "prensadaodevagas-com-br"
version = "0.1.0"
description = "Este é o repositório ajuda na geração do site prensadaodevagas.com.br"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ohmyscrapper>=0.9.0",
]
